added DL verification
onroadeld/event-consumer pull request #15
Opened 2021-07-30 14:50 UTC by asariev

2021-07-30 17:26 UTC, onroadeld requested changes
ELD-FUNC-4.1.2.2 says drivers license and issued state should be required when creating DRIVER accounts. Should we make it a required and validate accordingly?

2021-07-30 17:26 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/service/validator/CreateUserRequestValidator.java
> +    }
According to  ELD-FUNC 4.1.2.4 it should be on per motor carrier (company) level, no? So basically if driver changes his motor carrier he should be able to register again on our system with a different company?

2021-07-30 17:26 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/domain/model/DriversLicense.java
> +  private String driverLicenseNumber;
I think we can omit `driverLicense` part here as the class name already says that it's DriversLicense, no?

Current -> `DriversLicense.number`
New      -> `DriversLicense.driversLicenseNumber`

2021-07-30 17:26 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/domain/model/DriversLicense.java
> +  private String issuedState; // For UI, it should be dropdown, select state code
How about using enum and allowing only those they are truly valid?

2021-07-30 17:26 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/service/UserService.java
> +    }
Why we are changing the value here, maybe returning 400 and asking for a valid number with error message would be better?

2021-07-30 17:26 UTC, onroadeld commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
We have `schema.sql` class which is used to create ddl, no?

2021-08-02 06:49 UTC, asariev commented on src/main/java/io/onroad/eventconsumer/domain/model/DriversLicense.java
> +  private String driverLicenseNumber;
we can leave as its then

2021-08-02 06:50 UTC, asariev commented on src/main/java/io/onroad/eventconsumer/domain/model/DriversLicense.java
> +  private String issuedState; // For UI, it should be dropdown, select state code
Baary State code enum kylyp kirgizip koioiunbu?

2021-08-02 06:56 UTC, asariev commented on src/main/java/io/onroad/eventconsumer/service/UserService.java
> +    }
In DL, format is XXXX-XXX-XXXX, but in report we should generate without dash, I was thinking just removed the extra special characters. Or from FrontEnd we need to specify the format

2021-08-02 06:56 UTC, asariev commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
Mende run bolboitat, super user'di da manual run kylyp alamyn

2021-08-02 11:10 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/domain/model/DriversLicense.java
> +  private String issuedState; // For UI, it should be dropdown, select state code
ooba

2021-08-02 11:12 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/service/UserService.java
> +    }
If its only formatting difference then it should be handled on the frontend and frontend when saving should send only the data.

2021-08-02 11:12 UTC, onroadeld commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
Emne kata chygyp jatat?

2021-08-02 15:45 UTC, asariev commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
For running application, its giving me error that I have a new column. For test case's, schema is running first
should we add here:

`
@SpringBootApplication
public class EventConsumerApplication {

`

2021-08-02 15:49 UTC, asariev commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
Ech kandai error chykpaile

2021-08-03 09:47 UTC, onroadeld reviewed
Left tiny comment, all looks good .

2021-08-03 09:47 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/service/validator/GeneralValidator.java
> +    }
Let's delete this class.

2021-08-04 07:39 UTC, onroadeld approved these changes

2021-08-04 10:35 UTC, merged