Feature/refactor
onroadeld/event-consumer pull request #19
Opened 2021-08-19 09:45 UTC by asariev

2021-08-19 11:26 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/domain/mapper/LoginViewMapper.java
> +    loginView.setId(String.valueOf(user.getId()));
Why we need id during login?

2021-08-19 11:27 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/domain/dto/ProfileRequest.java
> +    private String id;
Let's use this API definition?

https://github.com/onroadeld/event-consumer/blob/main/docs/api.yml#L78

2021-08-19 11:32 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/api/DriverApi.java
> +    @PostMapping("/profile")
We could use this API definition for profile API

https://github.com/onroadeld/event-consumer/blob/main/docs/api.yml#L78

2021-08-19 11:44 UTC, asariev commented on src/main/java/io/onroad/eventconsumer/domain/mapper/LoginViewMapper.java
> +    loginView.setId(String.valueOf(user.getId()));
For mobile, they can hash two users with id, Mobile should keep two tokens at the same time for co-driver

2021-08-20 07:59 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/domain/mapper/LoginViewMapper.java
> +    loginView.setId(String.valueOf(user.getId()));
Dos, they should use the `/api/me` endpoint to fetch user related information or they can get the unique id from jwt token. JWT token can be easily decoded.

I have decoded this token

eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxLHN1cGVyLmFkbWluQG9ucm9hZC5pbyIsImlzcyI6Im9ucm9hZC5pbyIsImlhdCI6MTYyNzIyNzEwOCwiZXhwIjoxNjI3ODMxOTA4fQ.yrLqJIO4vKrYY5UEG1DwpGxz8Z4dLSGyjDYe_nvjoTciJXPVYeWS3bkFJPTxFt7aHW4sfD35Q7gGe2XGkvnsUw

Using 

https://jwt.io/

```
{
  "sub": "1,super.admin@onroad.io",
  "iss": "onroad.io",
  "iat": 1627227108,
  "exp": 1627831908
}
```

As you can see sub contains id and email.

2021-08-20 08:01 UTC, onroadeld commented on src/test/java/io/onroad/eventconsumer/api/TestDriverApi.java
> +public class TestDriverApi {
This file names have been changed on master. Could you merge it and change accordingly here?

2021-08-20 08:07 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/service/UserService.java
> +    return userViewMapper.toUserView(loggedUser);
I see that UserView has the following properties

```
userView.setEmail(user.getUsername());
    userView.setFirstName(user.getFirstName());
    userView.setLastName(user.getLastName());
    userView.setDriverLicenseNumber(user.getDriversLicense()!= null ? user.getDriversLicense().getNumber() : "");
    
   Do we need more information on the profile page? For example company names, current duty status etc?
   
   We need to change api.yaml file that matches current implementation or the other way around. 
   
   Also let's remove `coDriver` from the `/api/me` endpoint documentation.

2021-08-20 09:54 UTC, onroadeld reviewed
Let's remove if these ones are also not needed

```
              company:
                type: object
                properties:
                  name:
                    type: string
              dutyStatus:
                type: object
                properties:
                  abbreviation:
                    example: OFF
                  dataCoding:
                    example: 1
                  name:
                    example: Off Duty

2021-08-20 09:55 UTC, onroadeld requested changes
Also `/api/me` expects user information under user property

```
user:
                type: object
                properties:
                  firstName:
                    type: string
                    example: Tomas
                  lastName:
                    type: string
                    example: Edison
                  email:
                    type: string
                    example: tomas.edison@onroadnetworks.com

2021-08-20 11:32 UTC, onroadeld approved these changes

2021-08-20 11:33 UTC, merged