Implemented Driver login/logout and Engine power up and down
onroadeld/event-consumer pull request #31
Opened 2021-09-19 18:44 UTC by asariev

2021-09-19 20:56 UTC, onroadeld requested changes
Nice job! Left some comments.

2021-09-19 20:56 UTC, onroadeld commented on docs/api.yml
> +                type: integer
These two have to be enums. See EventType and EventCode Enums

2021-09-19 20:56 UTC, onroadeld commented on docs/api.yml
> +                example: "2021-09-14T11:23:50.470Z"
Maybe it's better to keep date and time's separtely as it's written in docs? This way we don't have to parse datatimes in different formats.

2021-09-19 20:56 UTC, onroadeld commented on docs/api.yml
> +                type: integer
Also let's put examples to all properties

2021-09-19 20:56 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/api/EventApi.java
> +@Tag(name = "Events")
Let's remove this tags as we are relying on api.yml file for documentation.

2021-09-19 20:56 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/domain/object/CoordinatesObject.java
> +public class CoordinatesObject {
Let's remove `Object` part as it's a class and only instance of it is an object.

2021-09-19 20:56 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/service/validation/validator/CreateEventRequestValidator.java
> +  private final CreateEnginePowerUpDownEventValidator createEnginePowerUpDownEventValidator;
You can use Factory pattern to abstract the validators and get the correct one by event type.

https://refactoring.guru/design-patterns/factory-method

2021-09-19 20:56 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/service/validation/validator/CreateEventRequestValidator.java
> +        throw new ValidationException(ValidationExceptionType.EVENT_TYPE_UNKNOWN);
Basically this will go inside factory and the correct validator object is returned and all validators inherit from the same interface which has validate method.

2021-09-19 20:56 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/util/SequenceGenerator.java
> +        return Long.toHexString(max+1);
I believe this event sequence should be per driver, no? So each driver will have it's event sequence.

2021-09-19 20:56 UTC, onroadeld commented on src/main/resources/schema-mysql.sql
> +    created_utc_date_time datetime,
Maybe we save separately date and time?

2021-09-19 20:56 UTC, onroadeld commented on src/test/java/io/onroad/eventconsumer/api/TestEventApi.java
> +                .andExpect(status().isOk())
Let's use 201 for event creation.

2021-09-19 20:56 UTC, onroadeld commented on src/test/java/io/onroad/eventconsumer/api/TestEventApi.java
> +                .andExpect(status().isBadRequest()).andExpect(content().string(containsString("Method argument validation failed")));
Let's update api.yml with 400 as a bad request response.

2021-09-19 20:56 UTC, onroadeld commented on src/test/java/io/onroad/eventconsumer/api/TestEventApi.java
> +        assertEquals(eventView.getEventType(), EventType.CMV_ENGINES_POWER_UP_DOWN_ACTIVITY);
We could use https://joel-costigliola.github.io/assertj/ for more fluent code. Wdyt?

2021-09-19 20:56 UTC, onroadeld commented on src/main/java/io/onroad/eventconsumer/domain/mapper/EventCreateMapper.java
> +    return(c * r);
Let's remove this into separate helper classes if suitable? what do you think?

2021-09-21 10:00 UTC, asariev commented on docs/api.yml
> +                type: integer
updated

2021-09-21 10:00 UTC, asariev commented on docs/api.yml
> +                example: "2021-09-14T11:23:50.470Z"
updated

2021-09-21 10:00 UTC, asariev commented on src/main/java/io/onroad/eventconsumer/api/EventApi.java
> +@Tag(name = "Events")
removed

2021-09-21 10:01 UTC, asariev commented on src/main/java/io/onroad/eventconsumer/domain/object/CoordinatesObject.java
> +public class CoordinatesObject {
removed

2021-09-21 10:01 UTC, asariev commented on src/main/java/io/onroad/eventconsumer/service/validation/validator/CreateEventRequestValidator.java
> +  private final CreateEnginePowerUpDownEventValidator createEnginePowerUpDownEventValidator;
Implemented Factory method pattern design

2021-09-21 10:01 UTC, asariev commented on src/main/resources/schema-mysql.sql
> +    created_utc_date_time datetime,
updated

2021-09-21 10:01 UTC, asariev commented on src/test/java/io/onroad/eventconsumer/api/TestEventApi.java
> +                .andExpect(status().isOk())
udpaed

2021-09-21 10:01 UTC, asariev commented on src/test/java/io/onroad/eventconsumer/api/TestEventApi.java
> +                .andExpect(status().isBadRequest()).andExpect(content().string(containsString("Method argument validation failed")));
updated

2021-09-21 10:02 UTC, asariev commented on src/test/java/io/onroad/eventconsumer/api/TestEventApi.java
> +        assertEquals(eventView.getEventType(), EventType.CMV_ENGINES_POWER_UP_DOWN_ACTIVITY);
added dependency and implemented only for Event Tests, will continue using it. It has more functions for verificaiton

2021-09-21 10:02 UTC, asariev commented on src/main/java/io/onroad/eventconsumer/domain/mapper/EventCreateMapper.java
> +    return(c * r);
udpated

2021-09-21 10:08 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/service/validation/validator/ValidationFactory.java
> +                return new CreateDriverLoginLogoutEventValidator();
Let's inject these validators and reuse it

2021-09-21 10:08 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/util/HelperUtil.java
> +public class HelperUtil {
Maybe GeoHelper?

2021-09-21 10:22 UTC, asariev commented on src/main/java/io/onroad/eventconsumer/service/validation/validator/ValidationFactory.java
> +                return new CreateDriverLoginLogoutEventValidator();
I believe Injected in ValidationFactory

2021-09-21 10:23 UTC, asariev commented on src/main/java/io/onroad/eventconsumer/util/HelperUtil.java
> +public class HelperUtil {
updated

2021-09-21 10:31 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/service/validation/validator/ValidationFactory.java
> +                return new CreateDriverLoginLogoutEventValidator();
`@Autowired
private final CreateDriverLoginLogoutEventValidator createDriverLoginLogoutEventValidator;`

Ushundai kylsak JVM'de bir ele validator bolotta, bolboso ar bir requestte jany create bolot. :) Let's do it in the next PR.

2021-09-21 10:31 UTC, nursultanturdaliev commented on src/test/java/io/onroad/eventconsumer/api/TestEventApi.java
> +                .andExpect(status().isBadRequest()).andExpect(content().string(containsString("Method argument validation failed")));
updated on API.YML as well?

2021-09-21 10:31 UTC, nursultanturdaliev commented on docs/api.yml
> +        '200':
Delete should be 204 no?

2021-09-22 06:30 UTC, asariev commented on docs/api.yml
> +        '200':
updated, messed up with other editor

2021-09-22 08:12 UTC, onroadeld approved these changes

2021-09-22 08:14 UTC, merged