Wsdl
onroadeld/event-consumer pull request #54
Opened 2021-12-08 14:49 UTC by asariev

2021-12-10 09:57 UTC, nursultanturdaliev requested changes
I see that unit tests are missing)

2021-12-10 09:57 UTC, nursultanturdaliev commented on docs/api.yml
> +              sendReportType:
Let's use just reportType

2021-12-10 09:57 UTC, nursultanturdaliev commented on docs/api.yml
> -                type: string
Why did we remove these values?

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/EventConsumerApplication.java
> +    System.setProperty("java.net.useSystemProxies", "true");
This line can be removed.

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/EventConsumerApplication.java
> +  }
let's move this into `SoapConfiguration` class.

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/EventConsumerApplication.java
> +    String password = new BCryptPasswordEncoder().encode("YourStrong(!)Password1!");
This can be reverted too. I was testing something on 1.8 and it's just a remnant.

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/api/ReportApi.java
> +@RolesAllowed({Role.SUPER_ADMIN, Role.MOTOR_CARRIER_SUPPORT_PERSONNEL, Role.DRIVER})
Can people other than driver generate a report?

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/domain/dto/Report.java
> +    private String eldRegistrationId = "TEST";
These two values has to come from configuration, db or from request as they change per driver.

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/domain/dto/ReportRequest.java
> +    private String comment;
Is this the same thing as `outputFilecomment`? Let's use the same names if they are the same things.

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/domain/mapper/LoginViewMapper.java
> +    LoginView loginView = new LoginView();
This can be reverted too.

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/service/ReportService.java
> +        }
I would put this under validator logic as we are basically validating HTTP request body.

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/util/Constants.java
> +    public static String certFileName ="cacerts";
These values should be on the application.yml file as they change.

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/util/Constants.java
> +    public static String datePatern = "MMddyy'T'HH:mm:ss";
These ones too.

2021-12-10 09:57 UTC, nursultanturdaliev commented on src/main/java/io/onroad/eventconsumer/api/ReportApi.java
> +        return reportService.sendReport(reportRequest, user);
Let's keep track of all report generations in a DB table.

2021-12-10 13:45 UTC, onroadeld commented on docs/api.yml
> +              sendReportType:
done

2021-12-13 07:16 UTC, nursultanturdaliev approved these changes

2021-12-13 12:11 UTC, onroadeld approved these changes

2021-12-14 04:42 UTC, merged